### ISSUE TITLE
USER STORY: Poll Expiry Date

### ISSUE THREAD

**Issue by Taybe2** [Taybe2/LoveRunning#3]
As an **administrator** I can **pick an expiry date while publishing the poll** so that **the poll gets hidden automatically**

## Acceptance Criteria
- Acceptance Criteria 1: The poll should disappear at 11:59 PM on the target date
- Acceptance Criteria 2: The real estate of the "Poll" should be reserved on the homepage. A message that says "Stay tuned, a new poll is coming soon" should appear if no Poll is active.
- Acceptance Criteria 3: The administrator expiry date should be at least 3 days after the current date.

## Tasks
- [ ] Update admin module view: the poll design (HTML and CSS) to include date picker
- [ ] Update the website view: show "Stay tuned, a new poll is coming soon"
- [ ] Create a JavaScript function to validate the expiry date is at least after 3 days.
- [ ] Create a job to check expired Poll everyday at 11:59 PM and hide them
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality
