### ISSUE TITLE
USER STORY: Hide user identity

### ISSUE THREAD

**Issue by Taybe2** [Taybe2/LoveRunning#4]
As a **user** I can **hide my identity** so that **I can provide anonymous feedback**

## Acceptance Criteria
- Acceptance Criteria 1: The option should be provided as a checkbox
- Acceptance Criteria 2: The checkbox should be checked by default
- Acceptance Criteria 3: The option should appear next to the submit button
- Acceptance Criteria 4: After submitting the default submission confirmation should be adjusted to include the use name.

## Tasks
- [ ] Update the view: the poll design (HTML and CSS) to include the checkbox and to show the name of the submitter
- [ ] Create a new field in the model to track the username
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the fuctionality
