### ISSUE TITLE
USER STORY: Poll Results

### ISSUE THREAD

**Issue by Taybe2** [Taybe2/LoveRunning#5]
As an **administrator** I can **view poll results** so that **can know my users feedback**

## Acceptance Criteria
- Acceptance Criteria 1: Administrator can see the feedback for each question.
- Acceptance Criteria 1: The poll results are updated after each user submit.

## Tasks
- [ ] Update admin module view: add "View Poll Results" for each poll
- [ ] Add Poll Results design
- [ ] Update controller function
- [ ] Update unit test scripts
- [ ] Test the functionality
